services:
  db:
    image: postgres:16
    container_name: bp_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: bp_backend
    depends_on:
      - db
    environment:
      DB_DOMAIN: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JPA_SHOW_SQL: ${JPA_SHOW_SQL}
      JPA_DDL_AUTO: ${JPA_DDL_AUTO}
      FLYWAY_ENABLED: ${FLYWAY_ENABLED}
      FLYWAY_LOCATIONS: ${FLYWAY_LOCATIONS}
      FLYWAY_BASELINE_ON_MIGRATE: ${FLYWAY_BASELINE_ON_MIGRATE}
    ports:
      - "8081:8080"
    restart: always

  # frontend:
  #   build:
  #     context: ./Frontend
  #   container_name: bp_frontend
  #   ports:
  #     - "5173:5173"
  #   restart: unless-stopped

volumes:
  pgdata:
