services:
  db:
    image: postgres:16
    container_name: bp_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: bp_backend
    depends_on:
      - db
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_DOMAIN: ${DB_DOMAIN}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JPA_SHOW_SQL: ${JPA_SHOW_SQL}
      JPA_DDL_AUTO: ${JPA_DDL_AUTO}
      FLYWAY_ENABLED: ${FLYWAY_ENABLED}
      FLYWAY_LOCATIONS: ${FLYWAY_LOCATIONS}
      FLYWAY_BASELINE_ON_MIGRATE: ${FLYWAY_BASELINE_ON_MIGRATE}
      MY_BANK_ENCRYPTION_SECRET_KEY: ${MY_BANK_ENCRYPTION_SECRET_KEY}
      PDF_SERVICE_URL: ${PDF_SERVICE_URL}
    ports:
      - "${EXPOSED_PORT}:${SERVER_PORT}"
    restart: always

  reporter:
    build:
      context: ./reporter
    container_name: bp_reporter
    ports:
      - "8083:8080"
    restart: always

  frontend:
    build:
      context: ./Frontend
      args:
        VITE_API_URL: ${BACKEND_URL}
    container_name: bp_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped

volumes:
  pgdata:
