server:
  port: 8082
spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${DB_DOMAIN:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:myBankDB}
    username: ${DB_USER:esterodr}
    password: ${DB_PASSWORD:MyS3cretP4ss}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
logging:
  level:
    root: WARN
    com.esterodr.backend: WARN
